AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal secure IAM role for deploying GenAI IDP patterns'

Parameters:
  MasterStackName:
    Type: String
    Description: Name of the master GenAI IDP stack
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*$'
    ConstraintDescription: Must be a valid CloudFormation stack name
  
  DeployerGroupName:
    Type: String
    Description: IAM group name for pattern deployers
    Default: 'GenAI-IDP-Deployers-Secure'

Resources:
  AllPatternsDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${MasterStackName}-AllPatterns-Deployer-Secure'
      Description: 'Minimal secure role for deploying all GenAI IDP patterns'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'aws:RequestedRegion': !Ref 'AWS::Region'
          - Effect: Allow
            Principal:
              Service: 'cloudformation.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
      Policies:
        - PolicyName: CloudFormationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'cloudformation:*'
                Resource: '*'
              - Effect: Deny
                Action:
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:DeleteStack'
                Resource: '*'
                Condition:
                  StringNotLike:
                    'cloudformation:StackName':
                      - !Sub '${MasterStackName}*'
                      - !Sub '${MasterStackName}'
        - PolicyName: LambdaAndCompute
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:*'
                  - 'sagemaker:*'
                  - 'application-autoscaling:*'
                Resource: '*'
        - PolicyName: AIAndData
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:*'
                  - 'textract:*'
                  - 'states:*'
                  - 'dynamodb:*'
                Resource: '*'
        - PolicyName: StorageAndMessaging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                  - 'sns:*'
                  - 'sqs:*'
                  - 'events:*'
                Resource: '*'
        - PolicyName: IAMAndSecurity
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:*'
                  - 'cognito-idp:*'
                  - 'cognito-identity:*'
                  - 'appsync:*'
                  - 'kms:*'
                  - 'glue:*'
                  - 'ssm:*'
                Resource: '*'
        - PolicyName: MonitoringAndLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                  - 'cloudwatch:*'
                  - 'cloudfront:*'
                  - 'wafv2:*'
                  - 'aoss:*'
                  - 'codebuild:*'
                Resource: '*'

  DeployerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref DeployerGroupName
      Policies:
        - PolicyName: AssumeDeployerRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'sts:AssumeRole'
                Resource: !GetAtt AllPatternsDeployerRole.Arn
              - Effect: Allow
                Action:
                  - 'sts:TagSession'
                Resource: '*'

Outputs:
  AllPatternsDeployerRoleArn:
    Description: ARN of the secure all-patterns deployer role
    Value: !GetAtt AllPatternsDeployerRole.Arn